In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix

C:\Users\sadusumalli\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\sadusumalli\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
dataset=pd.read_csv("C:/AIandMLAssigment/train.csv")
dataset.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [3]:
dataset = dataset.drop(['PassengerId','Name','Ticket','Cabin'], axis=1)

In [4]:
le = LabelEncoder()
dataset['Sex'] = le.fit_transform(dataset['Sex'])
dataset['Embarked'] = le.fit_transform(dataset['Embarked'])

In [5]:
def find(col):
    x = dataset.drop([col], axis=1)
    y = dataset[col]
    train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state = 42)
    model = BernoulliNB()
    model.fit(train_x, train_y)
    ypred = model.predict(test_x)
    print(f"Accuracy score is {accuracy_score(test_y, ypred)}")
    print("-------------------------------------")
    print(f"Confusion Matrix: \n{confusion_matrix(test_y, ypred)}")

In [6]:
find('Pclass')

Accuracy score is 0.5786516853932584
-------------------------------------
Confusion Matrix: 
[[15 10 19]
 [ 0  8 34]
 [ 6  6 80]]


In [7]:
find('SibSp')

Accuracy score is 0.6910112359550562
-------------------------------------
Confusion Matrix: 
[[108  17   0   0   0   0]
 [ 28  15   0   0   0   0]
 [  3   2   0   0   0   0]
 [  1   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  0   1   0   0   0   0]]


In [8]:
find('Sex')

Accuracy score is 0.797752808988764
-------------------------------------
Confusion Matrix: 
[[53 20]
 [16 89]]


In [9]:
find('Parch')

Accuracy score is 0.6966292134831461
-------------------------------------
Confusion Matrix: 
[[118  15   0   0   0]
 [ 24   6   0   0   0]
 [ 10   2   0   0   0]
 [  1   0   0   0   0]
 [  1   1   0   0   0]]


In [10]:
find('Embarked')

Accuracy score is 0.7303370786516854
-------------------------------------
Confusion Matrix: 
[[  0   0  36]
 [  0   0  12]
 [  0   0 130]]
