In [1]:

#1. Create a 3x3x3 array with random values



import numpy as np
a = np.random.random((3,3,3))
print("3x3x3 array with random values",a)


3x3x3 array with random values [[[0.17608374 0.53392454 0.59778188]
  [0.91255247 0.95768463 0.74709564]
  [0.26756221 0.25348046 0.25101471]]

 [[0.34365914 0.86526237 0.50185223]
  [0.25716426 0.12125145 0.80003062]
  [0.72722187 0.47910672 0.55449549]]

 [[0.11874584 0.68263881 0.3658785 ]
  [0.35861    0.13070638 0.49459784]
  [0.76035765 0.86876489 0.42080286]]]


In [2]:
#2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


import numpy as np
a= np.diag([1, 2, 3, 4, 5])
print("5x5 matrix with values 1,2,3,4,5 just below the diagonal",a)

5x5 matrix with values 1,2,3,4,5 just below the diagonal [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [3]:
#3.Create a 8x8 matrix and fill it with a checkerboard pattern
import numpy as np
a= np.ones((8,8))
print("Checkerboard pattern is :")
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

Checkerboard pattern is :
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
#4.Normalize a 5x5 random matrix

import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)


Original Array:
[[0.78106036 0.15340984 0.40426982 0.86012235 0.57694925]
 [0.26656921 0.46740924 0.03771516 0.10558207 0.45320196]
 [0.62066156 0.58156455 0.81942763 0.1824461  0.50901716]
 [0.96750839 0.75154575 0.35047463 0.1079256  0.6000149 ]
 [0.46656102 0.00786528 0.96831935 0.16658864 0.14851452]]
After normalization:
[[0.80503077 0.15153724 0.41272619 0.88734808 0.59251555]
 [0.26935586 0.47846532 0.03107893 0.1017402  0.46367306]
 [0.63802768 0.59732088 0.84497778 0.18176905 0.52178641]
 [0.99915565 0.77430092 0.35671602 0.10418022 0.61653091]
 [0.47758217 0.         1.         0.16525866 0.14644036]]


In [6]:
#5.How to find common values between two arrays
import numpy as np
array1 = np.array([40, 50, 80, 90])
print("Array1: ",array1)
array2 = [50, 80, 90]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [40 50 80 90]
Array2:  [50, 80, 90]
Common values between two arrays:
[50 80 90]


In [7]:
#6.How to get the dates of yesterday, today and tomorrow
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


In [13]:
#7.Consider two random array A and B, check if they are equal
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,4,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 0 1 1 0 1]
Second array:
[2 0 2 3 0 2]
Test above two arrays are equal or not!
False


In [14]:
#8.Create random vector of size 10 and replace the maximum value by 0
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] =0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.49884023 0.21571117 0.74057891 0.49069791 0.65468527 0.77909957
 0.63961293 0.31385848 0.48000965 0.63151339]
Maximum value replaced by 0:
[0.49884023 0.21571117 0.74057891 0.49069791 0.65468527 0.
 0.63961293 0.31385848 0.48000965 0.63151339]


In [16]:
#9. How to print all the values of an array?

import numpy as np
import sys
nums = np.arange(10)
np.set_printoptions(threshold=sys.maxsize)
print(nums)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
# 10.Subtract the mean of each row of a matrix
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 5)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.31041931 0.90488925 0.07765624 0.60600428 0.06973621]
 [0.82918128 0.07761658 0.11504492 0.19314736 0.31448979]
 [0.56211113 0.47921558 0.79607839 0.18081699 0.8352868 ]
 [0.7218805  0.19577753 0.33605738 0.76298406 0.79050666]
 [0.45725244 0.42782836 0.00317382 0.04420998 0.48966722]]

Subtract the mean of each row of the said matrix:

[[-0.08332175  0.51114819 -0.31608482  0.21226322 -0.32400485]
 [ 0.5232853  -0.22827941 -0.19085106 -0.11274863  0.0085938 ]
 [-0.00859064 -0.0914862   0.22537661 -0.38988478  0.26458502]
 [ 0.16043928 -0.3656637  -0.22538385  0.20154283  0.22906544]
 [ 0.17282608  0.143402   -0.28125255 -0.24021638  0.20524085]]


In [20]:
#11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

import numpy as np
A = np.array([4,5,36])
B = np.array([70,80,90])
I = np.array([0,1,1])
np.add.at(A, I, B)
print(A)

[ 74 175  36]


In [23]:
# 12.How to get the diagonal of a dot product?
import numpy as np
a = np.random.randint(0, 5, (2,2))
b = np.random.randint(0, 5, (2,2))

print(a.dot(b))

np.diagonal(a.dot(b))
print(np.einsum('ij,ji->i', a,b))

[[ 0 21]
 [ 0  6]]
[0 6]


In [24]:
#13.How to find the most frequent value in an array
import numpy as np
x = np.random.randint(10, 20, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[14 10 10 12 10 12 17 11 15 15 10 14 14 10 19 15 17 14 15 11 11 14 17 13
 17 15 17 14 18 14 10 14 18 16 12 19 12 18 15 10]
Most frequent value in the above array:
14


In [25]:
#14.How to get the n largest values of an array
import numpy as np
x = np.arange(5)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4]
[4]


In [28]:
#15.How to create a record array from a regular array

import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['apple','banana','gova','grapes'])
a3=np.array([10,40,20,80])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])


(1, 'apple', 10)
(2, 'banana', 40)
(3, 'gova', 20)
